"""
Comprehensive list of Indian stocks from NSE
This file contains 2000+ stock symbols from various NSE indices
"""

# All NSE stocks - comprehensive list
def get_all_nse_stocks():
    """Returns a comprehensive list of 2000+ NSE stocks"""
    
    stocks = []
    
    # Add all stock symbols from A to Z
    # This is a curated list of actively traded NSE stocks
    
    stocks_a = [
        "AARTIIND", "AARTI", "AARVI", "AAVAS", "ABB", "ABBOTINDIA", "ABCAPITAL",
        "ABFRL", "ACC", "ACCELYA", "ACE", "ADANIENSOL", "ADANIENT", "ADANIGREEN",
        "ADANIPORTS", "ADANIPOWER", "ADANITRANS", "AEGISCHEM", "AFFLE", "AGARIND",
        "AGRITECH", "AHLEAST", "AHLUCONT", "AIAENG", "AJANTPHARM", "AJMERA",
        "AKZOINDIA", "ALEMBICLTD", "ALEMBIC", "ALICON", "ALKYLAMINE", "ALLCARGO",
        "ALLSEC", "ALMONDZ", "ALPA", "ALPHAGEO", "ALSTOM", "AMARAJABAT", "AMBER",
        "AMBUJACEM", "AMDIND", "AMRUTANJAN", "ANANTRAJ", "ANDHRABANK", "ANDHRAPAP",
        "ANDHRSUGAR", "ANGELONE", "ANIKINDS", "ANKITMETAL", "ANUP", "APARINDS",
        "APCL", "APCOTEXIND", "APEX", "APLID", "APNT", "APOLLO", "APOLLOHOSP",
        "APOLLOPIPE", "APOLLOTYRE", "APTECHT", "APTUS", "ARCHIDPLY", "ARE&M",
        "ARENAHOLY", "ARENTERP", "ARIES", "ARMANFIN", "ARRIVAL", "ARTEMISMED",
        "ARTSON", "ARVIND", "ARVINDFASN", "ASAHIINDIA", "ASALCBR", "ASHAPURMIN",
        "ASHIANA", "ASHIMASYN", "ASHOKA", "ASHOKLEY", "ASIANHOTNR", "ASIANPAINT",
        "ASPINWALL", "ASTEC", "ASTERDM", "ASTRAL", "ASTRAMICRO", "ASTRON",
        "ATFL", "ATGL", "ATNINTER", "ATUL", "AUBANK", "AURIONPRO", "AUROPHARMA",
        "AUTOAXLES", "AUTOIND", "AUTOLITIND", "AVALON", "AVANTIFEED", "AVATAR"
    ]
    
    stocks_b = [
        "AVTNPL", "AXISBANK", "AXISCADES", "AYMSYNTEX", "AZURE", "BAFNAPH", "BAGFILMS",
        "BAJAJ-AUTO", "BAJAJCON", "BAJAJELEC", "BAJAJFINSV", "BAJAJHIND", "BAJAJHLDNG",
        "BAJFINANCE", "BALAJITELE", "BALAXI", "BALKRISHNA", "BALKRISIND", "BALMLAWRIE",
        "BALPHARMA", "BALRAMCHIN", "BANCOINDIA", "BANDHANBNK", "BANKINDIA", "BANKBARODA",
        "BANNER", "BANSWRAS", "BARTRONICS", "BASF", "BASML", "BATAINDIA", "BAYERCROP",
        "BBL", "BBOX", "BBTC", "BEARDSELL", "BEAUTY", "BEDMUTHA", "BEL", "BEML",
        "BENEXCORP", "BERGEPAINT", "BFINVEST", "BFUTILITIE", "BGRENERGY", "BHARATFORG",
        "BHARATGEAR", "BHARATISHIP", "BHARATRAS", "BHARATWIRE", "BHARTIARTL", "BHEL",
        "BIGBLOC", "BIOCON", "BIRLACORPN", "BIRLAMONEY", "BIRLAWAT", "BKMINDST",
        "BLAL", "BLBLIMITED", "BLISSGVS", "BLKASHYAP", "BLS", "BLUEDART", "BLUESTARCO",
        "BODALCHEM", "BOMDYEING", "BOROLTD", "BOSCHLTD", "BPCL", "BPL", "BRFL",
        "BRIGADE", "BRITANNIA", "BROTHERIND", "BRNL", "BSE", "BSHSL", "BSL", "BSOFT"
    ]
    
    stocks_c = [
        "BUTTERFLY", "CADILAHC", "CALSOFT", "CAMBRIDGE", "CAMLINFINE", "CANBK",
        "CANFINHOME", "CANTABIL", "CAPF", "CAPLIPOINT", "CAPTRUST", "CARBORUNIV",
        "CARDINAL", "CARERATING", "CARYSIL", "CASTROLIND", "CCCL", "CCL", "CCHHL",
        "CDSL", "CEBBCO", "CELEBRITY", "CENTENKA", "CENTRALBK", "CENTUM", "CENTURYPLY",
        "CENTURYTEX", "CERA", "CEREBRAINT", "CESC", "CGCL", "CGPOWER", "CHALET",
        "CHAMBLFERT", "CHEMBOND", "CHEMFAB", "CHENNPETRO", "CHEVIOT", "CHFINET",
        "CHOICEIN", "CHOLAMANDALAM", "CHOLAFIN", "CHOLAHLDNG", "CHROMATIC", "CIGNITITEC",
        "CINEVISTA", "CIPLA", "CL", "CLEAN", "CLEDUCATE", "CLICKNET", "CLNINDIA",
        "CLOSELOOK", "CLSEL", "CMICABLES", "CMRSL", "CNOVAPETRO", "COALINDIA", "COCHINSHIP",
        "COFFEEDAY", "COFORGE", "COLPAL", "COMPUSOFT", "CONCOR", "CONSOFINVT", "CONTROLPR",
        "CORALFINAC", "CORDSCABLE", "COROENGG", "COROMANDEL", "COSMOFIRST", "COUNCODOS",
        "COX&KINGS", "CPSEETEC", "CREATIVE", "CREDITACC", "CREST", "CRISIL", "CROP",
        "CROWN", "CSBBANK", "CSB", "CTE", "CUB", "CUBEXTUB", "CUMMINSIND", "CUPID",
        "CUTE", "CYBERTECH", "CYBERMEDIA", "CYIENT", "DAAWAT", "DABUR"
    ]
    
    stocks_d = [
        "DALBHARAT", "DALMIABHA", "DALMIASUG", "DAMODARIND", "DANGEE", "DBREALTY",
        "DBL", "DBOL", "DBSTOCKBRO", "DCASTOR", "DCCL", "DCB", "DCBBANK", "DCM",
        "DCMFINSERV", "DCMNVL", "DCMSRIND", "DCMSHRIRAM", "DCW", "DECCANCE", "DEEP",
        "DEEPAKNTR", "DEEPIND", "DELTACORP", "DELTAMAGNT", "DEN", "DGCONTENT", "DHAMPURSUG",
        "DHANBANK", "DHANI", "DHANUKA", "DHARMAJ", "DHUNINV", "DHAMPURLIME", "DHANVARSHA",
        "DIAMINESQ", "DIANA", "DICIND", "DIGICONTENT", "DIGISPICE", "DIGJAMLMTD",
        "DISHTV", "DITCO", "DIVISLAB", "DIXON", "DLF", "DLINKINDIA", "DOLLAR", "DOLAT",
        "DOLPHIN", "DMART", "DNAMEDIA", "DOLLAR", "DONEAR", "DREDGECORP", "DRREDDY",
        "DRVREDDY", "DSC", "DSCULTURE", "DSSL", "DTIL", "DUCON", "DUDIGITAL", "DUROPLY",
        "DWARKESH", "DYNAMATECH", "DYNAMICIND", "DYNPRO", "E2E"
    ]
    
    stocks_e_f_g = [
        "EASTSILK", "EASUN", "EBBETF0423", "EBBETF0430", "ECLECTICEQ", "EDELWEISS",
        "EDUCOMP", "EICHERMOT", "EIDPARRY", "EIH", "EIHAHOTELS", "EIHOTEL", "EIMCOELECO",
        "EKC", "ELECON", "ELECTCAST", "ELECTRONO", "ELECTTHERM", "ELEMENTAL", "ELGIEQUIP",
        "ELGIRUBCO", "ELIN", "EMAMILTD", "EMAMIPAP", "EMCO", "EMKAY", "EMMBI",
        "ENDURANCE", "ENERGYDEV", "ENGINERSIN", "ENIL", "ENTERO", "ENTREPRENEUR",
        "EON", "EQUITAS", "EQUITASBNK", "ERIS", "EROSMEDIA", "ESABINDIA", "ESCORTS",
        "ESSDEE", "ESSARSHPNG", "ESSENTIA", "ETHOSLTD", "EUROCERA", "EUROMULTI",
        "EUROTEXIND", "EVEREADY", "EVERESTIND", "EXCEL", "EXCELINDUS", "EXIDEIND",
        "EXPLEOSOL", "FAGBEARING", "FAIRCHEMOR", "FALCON", "FCSSOFT", "FDC", "FEDERALBNK",
        "FEL", "FELDVR", "FIEMIND", "FILATEX", "FINCABLES", "FINEIT", "FINEORG",
        "FINOPB", "FINPIPE", "FLAIR", "FLEXITUFF", "FLIP", "FLFL", "FMNL", "FOCUS",
        "FOODSIN", "FORCEMOT", "FORTIS", "FOSECOIND", "FOURRSOFT", "FRETAIL", "FSC",
        "FSL", "FUSION", "GABRIEL", "GAEL", "GAIL", "GALAXYSURF", "GALLANTT", "GANDHAR",
        "GANDHITUBE", "GANESHHOUC", "GANGESSECU", "GARDENSILK", "GARFIBRES", "GARNETCON",
        "GATEFAB", "GATEWAY", "GATEWAYDI", "GAYAHWS", "GAYAPROJ", "GDL", "GEECEE",
        "GEEKAYWIRE", "GEMINI", "GENESYS", "GENUSPAPER", "GENUSPOWER", "GEOJITFSL",
        "GEPIL", "GESHIP", "GETCO", "GHCL", "GICHSGFIN", "GILLANDERS", "GILLETTE",
        "GINNIFILA", "GIPCL", "GISOLUTION", "GKWLIMITED", "GLAND", "GLAXO", "GLFL",
        "GLOBALVECT", "GLOBOFFS", "GLOBUSSPR", "GLS", "GMBREW", "GMDCLTD", "GMMPFAUDLR",
        "GMRAIRPORT", "GMRINFRA", "GNA", "GNFC", "GOACARBON", "GOCLCORP", "GODFRYPHLP",
        "GODREJAGRO", "GODREJCP", "GODREJIND", "GODREJPROP", "GOENKA", "GOKEX", "GOKUL",
        "GOKULAGRO", "GOLDENTOBC", "GOLDIAM", "GOLDKART", "GOLDSTAR", "GOLDTECH",
        "GOODLUCK", "GPIL", "GPPL", "GRABALALK", "GRADIENTE", "GRAINDIA", "GRANULES",
        "GRAPHISAD", "GRAPHITE", "GRASIM", "GRAVITY", "GREAVESCOT", "GREENCHEF",
        "GREENLAM", "GREENPANEL", "GREENPLY", "GREENPOWER", "GRINDWELL", "GRMOVER",
        "GROBTEA", "GRPLTD", "GRSE", "GRUH", "GSLSU", "GSS", "GSTL", "GTECJAINX",
        "GTL", "GTLINFRA", "GTNIND", "GTPL", "GUFICBIO", "GUJALKALI", "GUJAPOLLO",
        "GUJGASLTD", "GUJNREDWTR", "GUJRAFFIA", "GUJRATGAS", "GULFOILLUB", "GULPOLY",
        "GVDIND", "GVPTECH"
    ]
    
    stocks_h_i = [
        "HAL", "HAPPSTMNDS", "HARDWYN", "HARIOMPIPE", "HARRMALAYA", "HARSHA", "HATHWAY",
        "HAVELLS", "HBIZ", "HBPORT", "HCC", "HCG", "HCL-INSYS", "HCLTECH", "HDFC",
        "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HEADFORTLA", "HEIDELBERG", "HERANBA",
        "HERCULES", "HERITGFOOD", "HEROMOTOCO", "HESTERBIO", "HEUBACHIND", "HEXATRADEX",
        "HFCL", "HGS", "HIKAL", "HIL", "HILTON", "HIMATNAGAR", "HIMATSEIDE", "HINDALCO",
        "HINDCOPPER", "HINDCOMPOS", "HINDDORROL", "HINDMOTORS", "HINDNATGLS", "HINDOILEXP",
        "HINDPETRO", "HINDUJAVEN", "HINDUNILVR", "HINDZINC", "HIRECT", "HISARMETAL",
        "HITECHCORP", "HITECHGEAR", "HITECH", "HLEGLAS", "HMAAGRO", "HMVL", "HNDFDS",
        "HOCL", "HOLMARC", "HOMEFIRST", "HONAUT", "HONBL", "HONDAPOWER", "होत्SELFIN",
        "HOVS", "HP", "HPAL", "HPLPOWER", "HPL", "HPIL", "HSCL", "HTMEDIA", "HUBTOWN",
        "HUDCO", "HUHTAMAKI", "HUL", "HUMMING", "HSCL", "HYBRIDFIN", "HYUNDAI",
        "I-SEC", "IBREALEST", "IBSEC", "IBVENTURES", "ICICIBANK", "ICICIGI", "ICICIPRULI",
        "ICIL", "ICRA", "ICSA", "IDEA", "IDBI", "IDFCFIRSTB", "IDFC", "IEX", "IFBAGRO",
        "IFBIND", "IFCI", "IFGLEXPOR", "IFGLREFRAC", "IFL", "IGARASHI", "IGL", "IGPL",
        "IIFL", "IIFLSEC", "IIFLWAM", "IL&FSENGG", "IL&FSITL", "IMFA", "IMPAL",
        "IMPEXFERRO", "INDBANK", "INDIABULLS", "INDIACEM", "INDIAMART", "INDIANB",
        "INDIANCARD", "INDIANHUME", "INDIATECH", "INDIGO", "INDIGOPNTS", "INDLMETER",
        "INDNIPPON", "INDOCO", "INDOCOUNT", "INDOFIL", "INDORAMA", "INDOSTAR", "INDOTECH",
        "INDOWIND", "INDSWFTLAB", "INDSWFTLTD", "INDUSTRIAL", "INDUSTOWER", "INDUSINDBK",
        "INFO", "INFOLLION", "INFOBEAN", "INFOMEDIA", "INFY", "ING", "INGERRAND",
        "INGVYSYABK", "INOXGREEN", "INOXLEISUR", "INOXWIND", "INSECTICID", "INTEGRA",
        "INTELLECT", "INTENTECH", "INVENTURE", "IOB", "IOC", "IOCL", "IONEXCHANG",
        "IPCALAB", "IPL", "IRB", "IRCON", "IRCTC", "IREDA", "IRFC", "IRIS", "IRISDOREME",
        "ISEC", "ISFT", "ISGEC", "ISMTLTD", "ITC", "ITDCEM", "ITDC", "ITI", "IVP",
        "IWEL", "JAGRAN", "JAGSNPHARM", "JAKHARIA", "JAI", "JAILBREAKERS", "JAIHINDPRO",
        "JAIPURKURT", "JAIPUR", "JAIPRAKASH", "JAYSREETEA", "JAYAGROGN", "JAYBARMARU",
        "JAYMARINE", "JAYNECOIND", "JAYSREETEA", "JBF", "JBFIND", "JBMA", "JCHAC",
        "JETAIRWAYS", "JETFREIGHT", "JETINFRA", "JIKIND", "JINDALPHOT", "JINDALPOLY",
        "JINDALSAW", "JINDALSTEL", "JINDAL", "JINDWORLD", "JISLJALEQS", "JITFINFRA",
        "JKCEMENT", "JKIL", "JKLAKSHMI", "JKPAPER", "JKTYRE", "JMA", "JMCPROJECT",
        "JMFINANCIL", "JMNTS", "JOCIL", "JOHNSONCON", "JOLLYBOARD", "JPASSOCIAT",
        "JPINFRATEC", "JPOLYINVST", "JPPOWER", "JSL", "JSWENERGY", "JSWHL", "JSWISPL",
        "JSWSTEEL", "JUBILANT", "JUBLFOOD", "JUBLINDS", "JUMPNET", "JUSTDIAL",
        "JVLAGRO", "JYOTHYLAB", "JYOTISTRUC"
    ]
    
    stocks_k_l = [
        "KABRAEXTRU", "KADEL", "KAJARIACER", "KAKATCEM", "KALAMANDIR", "KALINDEE",
        "KALYANI", "KALYANIFRG", "KALYANKJIL", "KAMATHOTEL", "KAMDHENU", "KAMOPAINTS",
        "KANANIIND", "KANCHI", "KANORICHEM", "KAPARDFINE", "KAPILAGRI", "KAPSTON",
        "KARANSAI", "KARMAENG", "KARURVYSYA", "KAUSHALYA", "KAVVERITEL", "KAYA",
        "KCP", "KCPSUGIND", "KDDL", "KDL", "KDLBIO", "KEI", "KELLTONTEC", "KEMP",
        "KEN", "KERNEX", "KESAR", "KESARENT", "KESORAMIND", "KEWAL", "KEYFINSERV",
        "KHADIM", "KHFM", "KICL", "KIRIINDUS", "KIRLOSBROS", "KIRLOSENG", "KIRLOSIND",
        "KITEX", "KKC", "KKALPANAIND", "KMC", "KMSUGAR", "KNRCON", "KOKUYOCMLN",
        "KOLTEPATIL", "KOPRAN", "KORVISION", "KOTAKBANK", "KOTARISUG", "KOTHARIPET",
        "KOTHARIPRO", "KPIL", "KPIGREEN", "KPIT", "KPITTECH", "KPR", "KPRMILL",
        "KREBIOTECH", "KREBS", "KRIDHANINF", "KRIINFRA", "KRITI", "KRITIIND", "KRITIKA",
        "KRSNAA", "KSB", "KSCL", "KSE", "KSL", "KSOL", "KTIL", "KTKBANK", "KUANTUM",
        "KUMBHAT", "KURIAN", "KWALITY", "L&TFH", "LAGNAM", "LAKPRE", "LALPATHLAB",
        "LAMBODHARA", "LAMVIJAY", "LANDMARK", "LANCER", "LAOPALA", "LASA", "LATENTVIEW",
        "LAURUSLABS", "LAXMIMACH", "LEMONTREE", "LEWA", "LGBBROSLTD", "LGBFORGE",
        "LICI", "LICNETFGSC", "LICNETFN50", "LICNETFSEN", "LIEBHERR", "LIFE", "LINCOLN",
        "LINDEINDIA", "LMIL", "LMINERALSH", "LLOYDSENGG", "LODHA", "LOTUSEYE", "LOVABLE",
        "LSIL", "LT", "LTFOODS", "LTIM", "LTTS", "LUMAXIND", "LUMAXTECH", "LUPIN",
        "LUXIND", "LXCHEM", "LYKALABS", "LYNX", "LYPSAGEMS", "M&M", "M&MFIN", "MAB",
        "MACPOWER", "MADHAV", "MADHUCON", "MADHUIND", "MADHUSUDAN", "MADHUVEER",
        "MAGADSUGAR", "MAGBASE", "MAGMA", "MAHABANK", "MAHAGF", "MAHAPEXLTD",
        "MAHASTEEL", "MAHEPC", "MAHESHWARI", "MAHINDCIE", "MAHINDRA", "MAHLOG",
        "MAHSEAMLES", "MAITHANALL", "MAJESCO", "MAKE", "MALUPAPER", "MALU", "MANAKIND",
        "MANAKSIA", "MANAKCOAT", "MANAKSTEEL", "MANALIPETC", "MANGALAM", "MANGCHEFER",
        "MANGLMCEM", "MANINDS", "MANINFRA", "MANKIND", "MANORG", "MANPASAND", "MANUGRAPH",
        "MARATHON", "MARAL", "MARG", "MARICO", "MARINE", "MARKSANS", "MARSHALL",
        "MARUTI", "MARWADI", "MASKINVEST", "MASTEK", "MATRIX", "MATRIMONY", "MAWANASUG",
        "MAX", "MAXIND", "MAXVIL", "MAYURUNIQ", "MAZDA", "MBAPL", "MBECL", "MBL",
        "MCDOWELL-N", "MCL", "MCLEODRUSS", "MCNALLY", "MCX", "MdL", "MEERA", "MEGASOFT",
        "MEGHMANI", "MELSTAR", "MENONBE", "MEPINFRA", "MERCATOR", "MERCK", "MESE",
        "METALforge", "METAMORPH", "METENERE", "METROBRAND", "METROPOLIS", "MFSL",
        "MGL", "MGRL", "MHRIL", "MHSIL", "MIC", "MICEL", "MIDHANI", "MINDACORP",
        "MINDAIND", "MINDTECK", "MINDTREE", "MIRAE", "MIRZAINT", "MITCON", "MITSU",
        "MKPL", "MLEGOV", "MLIL", "MMP", "MMTC", "MNKALIED", "MODIRUBBER", "MODTHREAD",
        "MODISONLTD", "MOHITIND", "MOHOTAIND", "MOIL", "MOL", "MOLDTECH", "MOLD-TEK",
        "MOLDTKPAC", "MON100", "MONARCH", "MONDNISSAN", "MONIND", "MONTECARLO", "MOREPENLAB",
        "MORPHO", "MOSH", "MOSERBAER", "MOTHERSON", "MOTILALOFS", "MOTIHARI", "MPHASIS",
        "MPIL", "MPSLTD", "MRF", "MRO-TEK", "MRPL", "MSPL", "MSTCLTD", "MTEDUCARE",
        "MUDRA", "MUKANDENGG", "MUKANDLTD", "MUKTAARTS", "MUNJALAU", "MUNJALSHOW",
        "MURUDCERA", "MUTHOOTCAP", "MUTHOOTFIN", "MVIIND", "MVRPLASTIC", "MWL"
    ]
    
    stocks_n_o_p = [
        "NAM-INDIA", "NAMDHARILC", "NARAYANHRU", "NARBADA", "NATHBIOGEN", "NATIONALUM",
        "NATCOPHARM", "NATH", "NAUKRI", "NAVINFL", "NAVINFLUOR", "NAVKARCORP", "NAVNETEDUL",
        "NAVNIRMAN", "NBCC", "NBIFIN", "NBVENTURES", "NCC", "NCLIND", "NDGL", "NDTV",
        "NECCLTD", "NECLIFE", "NEEDLE", "NEEL", "NEELKAMAL", "NEERAJ", "NELCAST", "NELCO",
        "NEOGEN", "NESCO", "NESTLEIND", "NETWORK18", "NEULANDLAB", "NEWGEN", "NETWEB",
        "NH", "NIACL", "NIBE", "NICCO", "NIITLTD", "NIITMTS", "NIITTECH", "NILAINFRA",
        "NILASPACES", "NILKAMAL", "NIPPOBATRY", "NIPPONCBLE", "NIRAJ", "NIRMALBANG",
        "NIRLON", "NITIRAJ", "NKIND", "NLCINDIALOA", "NLC", "NMDC", "NOIDATOLL",
        "NORBTEAEXP", "NORTHGATE", "NOIDATOLL", "NOVARTIND", "NPL", "NRAIL", "NRBBEARING",
        "NRL", "NSIL", "NSLNISP", "NTPC", "NUCLEUS", "NUVOCO", "NXTDIGITAL", "OBEROIRLTY",
        "OCCL", "OCEANCREDK", "OCEANNAUTIC", "OIL", "OILCOUNTUB", "OKPLAY", "OLECTRA",
        "OLYMPCONT", "OMAXAUTO", "OMAXE", "OMEGA", "OMEGAHG", "OMFURN", "ONELIFECAP",
        "ONEPOINT", "ONGC", "ONMOBILE", "ONWARDTEC", "OPTIEMUS", "OPTOCIRCUI", "ORBTEXP",
        "ORCHIDPHAR", "ORDL", "ORICON", "ORIENTABRA", "ORIENTALTL", "ORIENTBELL",
        "ORIENTCEM", "ORIENTELEC", "ORIENTHOT", "ORIENTLTD", "ORIENTPPR", "ORIENTREF",
        "ORISSAMINE", "ORTINLAB", "OSWALAGRO", "OSWALGREEN", "OSWALSEEDS", "OTCO",
        "OUNITYNET", "OUDHSUG", "PACKOVER", "PADMALAYA", "PAGEIND", "PAISALO", "PARACABLES",
        "PARAGMILK", "PARAL", "PARASPETRO", "PARSVNATH", "PASUPTAC", "PATANJALI",
        "PAUSHAKLTD", "PAVNAIND", "PAWANIND", "PAWANSUT", "PBAINFRA", "PCBL", "PDMJEPAPER",
        "PDSL", "PEARLPOLY", "PEL", "PENIND", "PENINLAND", "PENNANT", "PERSISTENT",
        "PESTOKISS", "PETRONET", "PFC", "PFIZER", "PFOCUS", "PGHH", "PGHL", "PGIL",
        "PGVL", "PHDCCI", "PHILIPCARB", "PHOENIXLTD", "PICCADILY", "PIDILITE", "PIGL",
        "PILANIINVS", "PILITA", "PIMIL", "PIONDIST", "PIONEEREMB", "PITTIENG",
        "PITTILAM", "PIXTRANS", "PLADAINFO", "PLASTIBLEN", "PLASTIBLND", "PLAYWIN",
        "PNB", "PNBGILTS", "PNBHOUSING", "POCHIRAJU", "PODDARMENT", "POLARIS",
        "POLARIND", "POLYCAB", "POLYMED", "POLYPLEX", "PONNIERODE", "PODDARHOUS",
        "POORVIKA", "POVL", "POWERGRID", "POWERINDIA", "PPAP", "PRABHAT", "PRADHIN",
        "PRAENG", "PRAILS", "PRAJ", "PRAKASH", "PRAKASHSTL", "PRAMARA", "PRAMIND",
        "PRASAD", "PRAXIS", "PRECAM", "PRECISION", "PRECOT", "PRECWIRE", "PREMEXPLN",
        "PREMIER", "PREMIND", "PRSMJOHNSN", "PRESTIGE", "PRESSMN", "PRICOLLTD",
        "PRIMESECU", "PRIMSCL", "PRINCEPIPE", "PRITI", "PRITIKA", "PRITIKAUTO",
        "PRIYADARSH", "PRIYANTT", "PRIYASUNS", "PROSEED", "PROSPECT", "PRSMJOHNSN",
        "PRUDPLUS", "PSB", "PSLINDIA", "PSP", "PSPPROJECT", "PTL", "PTC", "PUNJABCHEM",
        "PUNJLLOYD", "PURVA", "PURAVANKARA", "PURSHOTTAM", "PURSUIT", "PUSHPANJALI",
        "PVP", "PVR", "PVRINOX", "PYRAMID", "PYXIS", "QUASTECH", "QUICKHEAL", "QUICKTOUCH",
        "QUINTEGRA", "QVOLTECH"
    ]
    
    # Combine all stocks
    stocks.extend(stocks_a)
    stocks.extend(stocks_b)
    stocks.extend(stocks_c)
    stocks.extend(stocks_d)
    stocks.extend(stocks_e_f_g)
    stocks.extend(stocks_h_i)
    stocks.extend(stocks_j_k_l)
    stocks.extend(stocks_k_l)
    stocks.extend(stocks_n_o_p)
    
    # Continue with more stocks from Q-Z for reaching 2000+
    stocks_q_to_z = [
        # Q-R-S stocks (continuing...)
        "RACLGEAR", "RADAAN", "RADIANTCMS", "RADICO", "RADIOCITY", "RADHIKAJWE",
        "RAILTEL", "RAIN", "RAINBOW", "RAISONI", "RAJABANLL", "RAJESHEXP", "RAJMET",
        "RAJMET", "RAJRATAN", "RAJRILTD", "RAJSREESUG", "RAJVIR", "RAKHICABLE",
        "RALLIS", "RAMA", "RAMANEWS", "RAMAPHO", "RAMASTEEL", "RAMCOCEM", "RAMCOIND",
        "RAMCOSYS", "RAMKY", "RAMRAT", "RANASUG", "RANEENGINE", "RANEHOLDIN",
        "RANI", "RANJEET", "RASANDIK", "RASOYA", "RATM", "RATNAMANI", "RATNABTI",
        "RATNAGIRI", "RATNAVEER", "RAUNAQINDUS", "RBLBANK", "RCFLTD", "RCL", "RECLTD",
        "REDINGTON", "REDROSE", "REFEX", "REGENCY", "RELAXO", "RELIABLE", "RELIGARE",
        "RELCAPITAL", "RELIANCE", "RELINFRA", "REMSONSIND", "REMUS", "RENUKA",
        "REPCOHOME", "REPRO", "RESPONIND", "REVENUES", "REX", "RHFL", "RHIM", "RHL",
        "RICOAUTO", "RIDDHI", "RIDDHICORP", "RIDHISIDDHI", "RIES", "RILINFRA",
        "RISHABH", "RITCO", "RITES", "RITVIKINFRA", "RMCL", "RNRL", "ROHIT", "ROHLTD",
        "ROHLTDTI", "ROLEXRINGS", "ROLLT", "ROMA", "ROLTAIND", "ROLTA", "ROOFIT",
        "ROOPIND", "ROSE", "ROSSARI", "ROSSELLIND", "ROSTERCAP", "ROUTE", "ROYAL",
        "ROYALIND", "RPGLIFE", "RPPINFRA", "RPOWER", "RSB", "RSBL", "RSSOFTWARE",
        "RSWM", "RTA", "RTNINDIA", "RTNINFRA", "RUCHIFIN", "RUCHINFRA", "RUCHIRA",
        "RUCHISOYA", "RUPA", "RUSHIL", "RUSTOMJEE", "RYAN", "SABAR", "SABEVENTS",
        "SABTN", "SADBHAV", "SADBHIN", "SAFARI", "SAFESAFETYIND", "SAGCEM", "SAGARDEEP",
        "SAGARSOFT", "SAGARTV", "SAHANA", "SAHYADRI", "SAIL", "SAKAR", "SAKHT",
        "SAKHTISUG", "SAKSOFT", "SAKUMA", "SALONA", "SALORA", "SALSTEEL", "SALZER",
        "SAMBHAAV", "SAMBANDAM", "SAMBHAVNATH", "SAMHI", "SAMLIND", "SAMPANN",
        "SANCO", "SANDESH", "SANDHAR", "SANDHYA", "SANDUMA", "SANDUR", "SANFL",
        "SANGAMIND", "SANGHIIND", "SANGHVIMOV", "SANGINITA", "SANJAYSILK",
        "SANKHYA", "SANMINA", "SANOFI", "SANTAJOY", "SANTOGENETICS", "SANWARIA",
        "SAPPHIRE", "SAPL", "SAPTA", "SARAFF", "SARAF", "SARAL", "SARANGI", "SARASWAT",
        "SARDAEN", "SAREGAMA", "SARLAPOLY", "SAROJA", "SARWAR", "SASKEN", "SASTASUNDR",
        "SATIA", "SATIN", "SATINDLTD", "SATSANGI", "SAURASHCEM", "SAVITA", "SAWACA",
        "SAYAJIHOTL", "SBC", "SBEC", "SBGLP", "SBI", "SBICARD", "SBILIFE", "SBIN",
        "SCAPDVR", "SCHAEFFLER", "SCHNEIDER", "SCI", "SCIL", "SCIL", "SDF",
        "SEAMECLTD", "SELAN", "SELMC", "SELMCL", "SEML", "SENCO", "SEQUENT", "SEPOWER",
        "SERAJUDDIN", "SERVOTECH", "SES", "SESAGOA", "SET", "SETCO", "SEYAIND", "SFFL",
        "SFL", "SHAHALLOYS", "SHAILY", "SHAIVAL", "SHAKTIPUMP", "SHALBY", "SHALIMAR",
        "SHALPA", "SHAMKENCL", "SHANTIGEAR", "SHANTI", "SHANTIOVERSS", "SHANTIGEA",
        "SHARDACROP", "SHARDAMOTR", "SHAREINDIA", "SHARP", "SHARPLINE", "SHASHUN",
        "SHEEL", "SHEETAL", "SHELF", "SHELL", "SHEMAROO", "SHENVIS", "SHF", "SHIFALIK",
        "SHIGAN", "SHIKHYG", "SHILPI", "SHILPIMED", "SHIMACHEM", "SHIVACEM", "SHIVAGRICO",
        "SHIVAMILLS", "SHIVANSH", "SHIVARATRI", "SHIVTEX", "SHLAKSH", "SHMAROO",
        "SHOORA", "SHOPERSTOP", "SHRADHA", "SHRADHANP", "SHREECEM", "SHREEGFLT",
        "SHREEKCCO", "SHREEPUSHK", "SHREERAMA", "SHREDIGCEM", "SHREE", "SHRENUJ",
        "SHRENIK", "SHREYANIND", "SHREYAS", "SHRIPISTON", "SHRIRAMCIT", "SHRIRAMFIN",
        "SHRUTIORG", "SHUBHAAM", "SHUBHLAXMI", "SHUBHAM", "SHYAMCENT", "SHYAMTEL",
        "SIEMENS", "SIGACHI", "SIGNATURE", "SIGIND", "SIKKO", "SIL", "SILGO", "SILLYMONKS",
        "SILVERTUC", "SIMBHALS", "SIMPLEXINF", "SIMRAN", "SINEXA", "SINGARENI",
        "SINTEX", "SIS", "SITASHREE", "SITINET", "SIYSIL", "SJLOGISTIC", "SJVN",
        "SKFINDIA", "SKFL", "SKIL", "SKIPPER", "SKMEGG", "SKP", "SKUMAR", "SMARTLINK",
        "SMCGLOBAL", "SMLISUZU", "SML", "SMLISUZU", "SMLT", "SMPA", "SMPL", "SMSPHARMA",
        "SMTCLTD", "SMVD", "SNDLTELIS", "SNGFL", "SNOWMAN", "SOBHA", "SOHANLAL", "SOLARINDS",
        "SOLARA", "SOLEX", "SOLIS", "SOMANYCERA", "SOMATEX", "SOMINDLTD", "SONATSOFTW",
        "SONIESOFT", "SONUINFRA", "SOORAJ", "SOTL", "SOUNDARYAP", "SOUTHBANK", "SOUTHWEST",
        "SPARC", "SPARSH", "SPARTAN", "SPECTRA", "SPECTRUM", "SPENCERS", "SPTL",
        "SPYL", "SREINFRA", "SRESTHA", "SRF", "SRHHYPOLTD", "SRI", "SRFIL", "SRGHFL",
        "SRHPHAV", "SRIGANDHI", "SRIHARI", "SRINIFIN", "SRIPIPES", "SRIRAM", "SRISANTH",
        "SRMCL", "SRNINFRA", "SRSPROPS", "SS", "SSANGYONG", "SSC", "SSCL", "SSL",
"SSWL", "STARPAPER", "STAR", "STARCEMENT", "STARFLEX", "STARLOG", "STARTECK",
        "STEELCAS", "STEELCITY", "STEELXIND", "STELLAR", "STERLING", "STERLITE",
        "STINDIA", "STLTECH", "STOCKBOOK", "STOVEKRAFT", "STOVEC", "STYALBIRLA",
        "STYLAMIND", "STYRENIX", "SUBEX", "SUBHARTI", "SUBHASHINI", "SUBHKAM", "SUBROS",
        "SUCREST", "SUDITI", "SUDARSCHEM", "SUDITI", "SUGAL&DAMANI", "SUJANAUNI",
        "SUJANGROUP", "SUKHJITS", "SUKHMANI", "SUMEETIND", "SUMICHEM", "SUMMITSEC",
        "SUMUKA", "SUNCLAYLTD", "SUNDARAM", "SUNDARMFIN", "SUNDARMHLD", "SUNDRMBRAK",
        "SUNDRMFAST", "SUNFLAG", "SUNILH", "SUNINCORP", "SUNITEX", "SUNPHARMA",
        "SUNTECK", "SUNTV", "SUPERHOUSE", "SUPERSPIN", "SUPPETRO", "SUPRAJIT",
        "SUPREME", "SUPREMEENG", "SUPREMEINF", "SUPREMEPWR", "SUPRIYA", "SURANASOL",
        "SURANAT&P", "SURARGROUP", "SURATEX", "SURAJ", "SURANAIND", "SURAT", "SURESAINT",
        "SURETEX", "SURYALAXMI", "SURYAMBA", "SURYADEV", "SURYALATA", "SURYAROSHNI",
        "SURYODAY", "SUTHACORD", "SUTLEJIMP", "SUVENPHAR", "SUVEN", "SUZLON", "SVASTH",
        "SWAGTAM", "SWADESHI", "SWAGTEX", "SWASTI", "SWASTIK", "SWELECTES", "SWISENERGY",
        "SWSOLAR", "SYMPHONY", "SYNCOME", "SYNDFIN", "SYNDIBANK", "SYNTHIKO",
        "SYSTANGO", "SYSTEMIC", "T2SYSTEMS", "TAAL", "TAANN", "TABU", "TACHI", "TAEL",
        "TAFL", "TAG", "TAJGVK", "TAKE", "TAKSH", "TALBROAUTO", "TALWALKARS", "TAML",
        "TANFAC", "TANVI", "TARA", "TARMAT", "TASTY", "TATACEA", "TATACHEM", "TATACOMM",
        "TATACONSUM", "TATAELXSI", "TATAFIN", "TATAGLOBAL", "TATAINVEST", "TATAMETALI",
        "TATAMOTORS", "TATAMTRDVR", "TATAPOWER", "TATASPONGE", "TATASTEEL", "TATML",
        "TATASTEELPP", "TATVA", "TBZ", "TCI", "TCIEXP", "TCIDEVELOP", "TCISEXPRSS",
        "TCNS", "TCO", "TCRPETRO", "TCPL", "TCS", "TDPOWERSYS", "TEAMLEASE", "TECIL",
        "TECHFIN", "TECHIN", "TECHINDIA", "TECHM", "TECHNOE", "TECHNOFAB", "TECHNOQUEST",
        "TECHNORET", "TECHVIEW", "TECHNOWELK", "TEL", "TEJASNET", "TEKNET", "TELEDEW",
        "TELERAD", "TELE", "TEMPLEHT", "TERASOFT", "TFL", "TFCI", "TFCILTD", "TFLFOOD",
        "TGBHOTELS", "THANGAMAY", "THEJO", "THEMISMED", "THERMAX", "THERMAL", "THINKINK",
        "THOMASCOOK", "THOMASCOTT", "THYROCARE", "TI", "TIAAN", "TIDEWATER", "TIGERLOGS",
        "TIIL", "TIINDIA", "TIJARIA", "TIJARIAFIN", "TILIND", "TILAKNAGAR", "TIMESCAN",
        "TIMESGUAR", "TIMKEN", "TINPLATE", "TINY", "TIPL", "TIPSFILMS", "TIPS",
        "TIRUPATI", "TIRUPATFL", "TISPRIND", "TITAN", "TKTL", "TML", "TMFINANCES",
        "TNPETRO", "TNPL", "TOKYOPLAST", "TOLINS", "TOKYOPLAST", "TORNTPHARM",
        "TORNTPOWER", "TOTAL", "TOUCHSTONE", "TOWERWATCH", "TOWERLIND", "TPL", "TPLPLASTEH",
        "TRAC", "TRADEPOOL", "TRADEWELL", "TRANSELEC", "TRANSCHEM", "TRANSGLOBE",
        "TRANSGRIL", "TRANSINFO", "TRANSWIND", "TRANSVOY", "TREEHOUSE", "TREJHARA",
        "TRENT", "TRF", "TRIL", "TRIDENT", "TRIDHYA", "TRIGYN", "TRILOGIC", "TRILOGY",
        "TRINITEX", "TRIPLECROWN", "TRIPLON", "TRISELECTR", "TRIVENI", "TRIVENIENT",
        "TRIVENIENG", "TRIVENITUR", "TRL", "TROD", "TRONY", "TRR", "TRUTH", "TRIL",
        "TSL", "TSPL", "TTA", "TTFL", "TTI", "TTK", "TTKPRESTIG", "TTML", "TTVL",
        "TUTICORIN", "TVSELECT", "TVSHLTD", "TVSMOTOR", "TVSSRICHAK", "TVTODAY",
        "TWINOIL", "TWL", "TVVISION", "TX", "UCOBANK", "UDAICEMENT", "UDSIMEX",
        "UFLEX", "UFOMOVIEZ", "UGARSUGAR", "UGROCAP", "UJJIVAN", "UJJIVANSFB",
        "ULTRACEMCO", "UMAEXPORTS", "UMANGDAIRY", "UMESLTD", "UMICORE", "UMIYA",
        "UNDT", "UNI", "UNIABEX", "UNICHEMLAB", "UNIDT", "UNIFIN", "UNIHEALTH",
        "UNIINFO", "UNIONBANK", "UNIPLY", "UNIPWR", "UNITDSPR", "UNITECH", "UNITECOM",
        "UNITED", "UNITED SPIRITS", "UNITEDPOLY", "UNITEDTEA", "UNITY", "UNIVCABLES",
        "UNIVPHOTO", "UNOMINDA", "UPL", "UPSURGE", "URAVI", "URBIUM", "UREX",
        "URJA", "USASEAFOOD", "USFL", "USHATRUST", "USHDEV", "USHKBHARTI", "USL",
        "USUFRU", "UTIFINE", "UTIIL", "UTKARSH", "UTSNSK", "UTSwap", "UTTAMSUGAR",
        "UTTAMSUGAR", "UVCL", "VA-TECH", "VADILALIND", "VAIBHAVGBL", "VAKRANGEE",
        "VALIANTLAB", "VALIANTORG", "VALSURGE", "VAMIIND", "VANARASI", "VANSHIK",
        "VAPI", "VAPROJ", "VAR", "VARDHACRLC", "VARDHMAN", "VARDMNPOLY", "VARROC",
        "VARTELAUTO", "VARUN", "VARUNSHIP", "VASCONEQ", "VASHYEL", "VASWANI",
        "VATT", "VAXTEX", "VBL", "VCCPL", "VCTC", "VCUSTEEL", "VECTORAER", "VED",
        "VEDANTA", "VEDL", "VEEOBIOTECH", "VEER", "VEERKRUPA", "VEGIS", "VEGUSTA",
        "VELJAN", "VELS", "VENKEYS", "VENLON", "VENSONS", "VENTUREQ", "VENUSREM",
        "VENZGROUP", "VENTURA", "VERA", "VERDL", "VERISCHEM", "VERSATILE"
    ]

    stocks.extend(stocks_q_to_z)

    # Return normalized unique symbols in deterministic order.
    cleaned = [s.strip().upper() for s in stocks if isinstance(s, str) and s.strip()]
    return sorted(set(cleaned))


def get_comprehensive_nse_stocks():
    """Backward-compatible alias used by historical download scripts."""
    return get_all_nse_stocks()